name: generate animation

on:
  # run automatically every 12 hours
  schedule:
    - cron: "0 */12 * * *"
  
  # allows to manually run the job at any time
  workflow_dispatch:
  
  # run on every push on the master branch
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      # generates a snake game from a github user's contributions graph, output a svg animation
      - name: Generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v2
        with:
          github_user_name: trunglienquy
          svg_out_path: dist/github-contribution-grid-snake.svg  # This outputs the main SVG file

      # Optionally generate a dark mode version
      - name: Generate github-contribution-grid-snake-dark.svg
        uses: Platane/snk/svg-only@v2
        with:
          github_user_name: trunglienquy
          svg_out_path: dist/github-contribution-grid-snake-dark.svg
          palette: github-dark  # Generate with dark palette

      # Push the content of <build_dir> to a branch
      # the content will be available at https://raw.githubusercontent.com/<github_user>/<repository>/<target_branch>/<file>
      - name: Push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v2.6.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
